# Generated by Django 5.0.2 on 2024-02-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Career', '0004_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course')),
                ('career', models.ManyToManyField(related_name='courses_in', to='Career.career')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialtype', models.CharField(choices=[('News', 'News'), ('Urls', 'Urls'), ('PDF', 'PDF'), ('Videos', 'Videos'), ('Test', 'Test')], default='PDF', max_length=10)),
                ('link', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to='course/materials')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Course.course')),
            ],
        ),
    ]
