# Generated by Django 5.0.2 on 2024-02-06 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_admin_course_professors_course_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='asynchronous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='Course.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
