# Generated by Django 5.0.2 on 2024-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seccion',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
