# Generated by Django 5.0.2 on 2024-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_course_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
