# Generated by Django 5.0.2 on 2024-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_coursematerial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
