# Generated by Django 5.0.2 on 2024-02-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_alter_coursematerial_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
