# Generated by Django 5.0.2 on 2024-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
