# Generated by Django 5.0.2 on 2024-02-16 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typenotification', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(max_length=255)),
                ('send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sended', to=settings.AUTH_USER_MODEL)),
                ('send_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_receive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
