# Generated by Django 5.0.2 on 2024-02-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
