# Generated by Django 5.0.2 on 2024-02-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_alter_notification_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='send_for',
            new_name='send_to',
        ),
    ]
