# Generated by Django 5.0.2 on 2024-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_rename_send_for_notification_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_it',
            field=models.BooleanField(default=False),
        ),
    ]
