# Generated by Django 5.0.2 on 2024-02-11 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.CreateModel(
            name='QuizUserSolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification', models.IntegerField()),
                ('quiz', models.ManyToManyField(related_name='users', to='Quiz.quiz')),
                ('quiz_solution', models.ManyToManyField(related_name='solutions', to='Quiz.quizsolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
