# Generated by Django 5.0.2 on 2024-02-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_quiz_qualification_remove_quiz_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='typeof',
            new_name='typeoftest',
        ),
    ]
