# Generated by Django 5.0.2 on 2024-02-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_remove_quizproblem_solutions_quiz_solutions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='state',
            field=models.CharField(default='Not Available', max_length=25),
        ),
    ]
