# Generated by Django 5.0.2 on 2024-02-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_quiz_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizproblem',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizproblem',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizproblems', to='Quiz.quiz'),
            preserve_default=False,
        ),
    ]
