# Generated by Django 5.0.2 on 2024-02-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_remove_quizproblem_quiz_quizproblem_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsolution',
            name='problem',
        ),
        migrations.AddField(
            model_name='quizsolution',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problem_solutions', to='Quiz.quizproblem'),
            preserve_default=False,
        ),
    ]
