# Generated by Django 5.0.2 on 2024-02-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_remove_quizsolution_problem_quizsolution_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizusersolution',
            name='quiz_solution',
        ),
    ]
