# Generated by Django 5.0.2 on 2024-02-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_remove_quizusersolution_quiz_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizusersolution',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizusersolution',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Quiz.quiz'),
            preserve_default=False,
        ),
    ]
