# Generated by Django 5.0.2 on 2024-02-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_remove_quizusersolution_quiz_quizusersolution_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizproblem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quizsolution',
            name='image',
        ),
    ]
