# Generated by Django 5.0.2 on 2024-02-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_userresumecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresumecourse',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='Certificates'),
        ),
    ]
