# Generated by Django 5.0.2 on 2024-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_userresumecourse_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresumecourse',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='Certificates'),
        ),
    ]
