# Generated by Django 5.0.2 on 2024-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_alter_userresumecourse_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
    ]
