# Generated by Django 5.0.2 on 2024-02-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0016_quizusersolution_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusersolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
