# Generated by Django 5.0.2 on 2024-02-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0017_alter_quizusersolution_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizusersolution',
            name='created_at',
        ),
    ]
