# Generated by Django 5.0.2 on 2024-02-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0018_remove_quizusersolution_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizusersolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
