# Generated by Django 5.0.2 on 2024-02-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0004_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(null=True, upload_to='Facultades/'),
        ),
    ]
