# Generated by Django 5.0.2 on 2024-02-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
