# Generated by Django 5.0.2 on 2024-02-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_chatmessage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sent_to',
            new_name='send_to',
        ),
    ]
