# Generated by Django 5.0.2 on 2024-02-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_rename_sent_to_chatmessage_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/images'),
        ),
    ]
