# Generated by Django 5.0.2 on 2024-02-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_alter_chatroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
