# Generated by Django 5.0.2 on 2024-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='<django.db.models.fields.related.ForeignKey>/postsfile'),
        ),
    ]
