# Generated by Django 5.0.2 on 2024-02-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogpost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
