# Generated by Django 5.0.2 on 2024-02-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogpost_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='attachment_file',
            field=models.ImageField(blank=True, null=True, upload_to='postsimg'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='postsfile'),
        ),
    ]
