# Generated by Django 5.0.2 on 2024-02-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0004_career'),
        ('Course', '0001_initial'),
        ('User', '0002_alter_user_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='Career.career'),
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='users_in', to='Course.course'),
        ),
    ]
