# Generated by Django 5.0.2 on 2024-02-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='career',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
