# Generated by Django 5.0.2 on 2024-02-13 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_friends_friendshiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendshipsends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendshiprequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
