# Generated by Django 5.0.2 on 2024-02-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_friendshiprequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
